### ISSUE TITLE
Allow `::` in `collate_types!` macro

### ISSUE THREAD

**Issue by probablykasper** [oscartbeaumont/tauri-specta#1]
The `collate_types!` macro doesn't let you reference commands from other modules:
![image](https://user-images.githubusercontent.com/11315492/205193687-7a68a4ef-1eb5-46b6-b3cb-c9846915958b.png)

Tauri's `generate_handler!` macro does, so hopefully it's possible to make it work:
https://github.com/tauri-apps/tauri/blob/b6027b2dd298caccd879b8abf93532ea39354077/core/tauri-macros/src/lib.rs#L49-L51

**Comment by Brendonovich** [comment]
Turns out `macro_rules` isn't powerful enough to handle what `collate_types` needs to do, so we'll have to take some inspiration from Tauri and do a similar proc macro.

**Comment by oscartbeaumont** [comment]
I have started work on this. Will try and finish over the weekend.

**Comment by Brendonovich** [comment]
Should be fixed in 17e6c64e88bb2f9c1e7b5ef22b9f4afdd12955be

**Comment by probablykasper** [comment]
Unfortunately doesn't seem to work for me, unless I'm doing something wrong:
```rs
export_to_ts(collate_types![data::get_settings], "../bindings.ts").unwrap();
```
```
failed to resolve: could not find `__specta__fn__get_settings` in `data`
could not find `__specta__fn__get_settings` in `data`
```

**Comment by Brendonovich** [comment]
Hmm, will have to pay more attention to what the tauri's `generate_handler!` does

**Comment by Brendonovich** [comment]
Pretty much copied Tauri's macro code, should work on 44d5342ee7c98cc466e271a5bc548c8989d9be7f
