### ISSUE TITLE
missing Ok(()) in docs

### ISSUE THREAD

**Issue by Zercerium** [oscartbeaumont/tauri-specta#100]
Hi, thanks for specta.

There is a missing `Ok(())` in this position
https://github.com/oscartbeaumont/tauri-specta/blob/main/docs/v2.md#events

https://github.com/oscartbeaumont/tauri-specta/blob/1ad0a71a70239ed506c628bc2b808994285a8d94/docs/v2.md?plain=1#L112-L114
```diff
    tauri::Builder::default()
        .invoke_handler(invoke_handler)
       .setup(|app| {
           register_events(app);
+        Ok(())
       })
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
```

**Comment by oscartbeaumont** [comment]
Thanks!
