### ISSUE TITLE
Pass app handle to event listen callback

### ISSUE THREAD

**Issue by n1ght-hunter** [oscartbeaumont/tauri-specta#107]
i think it would make sense to pass a handle to the app in event listen callback similar to tauri menu events.
`.on_menu_event(move |app, event| {})`
so 
`...::listen(app.handle(), |event| {})`
would change to
`...::listen(app.handle(), |app, event| {})`

**Comment by oscartbeaumont** [comment]
It seems Tauri decided to not pass the `AppHandle` to the callback for their listeners and personally I think Tauri Specta should maintain an API as close to possible as what Tauri has, so i'm not sure we should implement this but I would be interested in other peoples thoughts.

The way you would get the `AppHandle` is as the following if anyone comes across and is confused what the code currently looks like:

```rust
.setup(|app| {
    ...::listen(app.handle(), {
       let app = app.clone();
       |event| {
           todo!();
       }
    })
})
```
