### ISSUE TITLE
Getting a lot of errors when trying to upgrade

### ISSUE THREAD

**Issue by kareemmahlees** [oscartbeaumont/tauri-specta#110]
## Issue
I am trying to update to the latest version of tauri-specta as of [this piece of code](https://github.com/oscartbeaumont/tauri-specta/blob/main/docs/v2.md#installation:~:text=Tauri%20Specta%20v2-,Installation,-Warning) and I am getting tons of issues when building tauri:
```
error[E0061]: this function takes 3 arguments but 2 arguments were supplied
   --> C:\Users\karee\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-2.0.0-beta.22\build.rs:380:5
    |
380 |     tauri_utils::acl::build::generate_docs(&permissions, &docs_out_dir)
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^----------------------------- an argument of type `&str` is missing
    |
note: function defined here
   --> C:\Users\karee\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tauri-utils-2.0.0-beta.19\src\acl\build.rs:240:8
    |
240 | pub fn generate_docs(
    |        ^^^^^^^^^^^^^
help: provide the argument
    |
380 |     tauri_utils::acl::build::generate_docs(&permissions, &docs_out_dir, /* &str */)
    |  
```

**Comment by wvffle** [comment]
I'm having the same issue after upgrading. I cannot get tauri-specta to work no matter the version of tauri or tauri-specta

**Comment by kareemmahlees** [comment]
@wvffle there is a [PR](#109) that fixes this but haven't been merged yet, the only workaround I came up with is to fork [this repo](https://github.com/reyamir/tauri-specta) which has the branch that fixes those _**until**_ the fix is merged.

**Comment by oscartbeaumont** [comment]
Closing in favor on `main` which is now on the latest Tauri.
