### ISSUE TITLE
Finish `Channel` support

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/tauri-specta#111]
- [ ] Blocked on https://github.com/tauri-apps/tauri/pull/10435
 - [ ] Remove feature gate
 - [ ] Documentation

**Comment by FlorianStasse** [comment]
Hello, it is marked as completed, but the docs still redirect to this issue. Is the documentation missing or is it still not completely implemented ?

I'm willing to spend some time helping on this issue as I need it for another project.

**Comment by oscartbeaumont** [comment]
I am fairly certain it's been implemented but just not documented.

I'm fairly sure it was added to the docs while this PR was open but while we were waiting for Tauri to merge a change upstream which was required to make it work.

Would love a PR for docs though if you have the time but all good if not!

**Comment by XurxoMF** [comment]
I've started using tauri_spectra today and I'ld love to see the docs for this! I want to do something similar to the DownloadEvent on the Tauri example but with tauri_spectra.

**Comment by XurxoMF** [comment]
I've to test it first. If I manage to get it working I'll make the docs.
Also, I probably can't test it because of a but I found. I'll open an issue in a few minutes.

**Comment by CodyAdam** [comment]
Any news on this issue ?

**Comment by oscartbeaumont** [comment]
It just works. If it doesn't open an issue.
