### ISSUE TITLE
`recursion_limit` issues with new `collect_commands`

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/tauri-specta#114]
Kinda shouldn't be surprised cause it's recursing on every `tt`.

https://discord.com/channels/616186924390023171/731495028677148753/1268605918304665730
https://discord.com/channels/1011665225809924136/1262072012998836364/1268577822675304512

**Comment by pauliesnug** [comment]
workaround for the meantime (put this on the top of your `main.rs`):
```rs
#![recursion_limit = "1024"]
```

**Comment by oscartbeaumont** [comment]
So all of the current macro's (`tauri_specta::collect_commands`, `specta::function::collect_functions` and `specta::function::fn_datatype`) go token by token (Eg. keyword, identifier, etc) and hence obviously the recursion limit is super easy to hit and I completly missed this in the original design.

As we can't set `recursion_limit` at a library/macro level this leaves the only option to rewrite the macros.

`collect_commands` and `collect_functions` can both be rewritten to remove recursion completly, however `fn_datatype` can't. This means as of the next update you can parse as many functions/commands as you want, yay!

Doing some testing `fn_datatype` in it's current form supports *any* number of generics (as these don't trigger recursion) but can only support at most 31 elements in a path (Eg. `"todo::".repeat(31)`). The side of each module name does not affect the number of supports elements due to us parsing by tokens (Eg. `todo` and `areallylongmodulename` are treated as one `tt` by the macro).

Realistically no one has this many nested modules (and if you do use crates!!!!!!!!) so I think we are going to live with this limitation for now.

If this limitation becomes a problem in the future we could optimise `fn_datatype` to recurse/parse in "batches" which could probally let us pretty easily double the max number of path segments at only the cost of more internal complexity. Alternatively we could change Specta's internals so we use `$name __specta__fn__` instead of the current `__specta__fn__ $name` which is ultimately why so much recursion is required.

Going to do a release in the next 5 mins or so with the fix.
