### ISSUE TITLE
Events broken in update

### ISSUE THREAD

**Issue by n1ght-hunter** [oscartbeaumont/tauri-specta#116]
the events on broken in the newest example.
due to the way they are stored in tauri only one place may use tauri specta.
i.e. if you have a plugin that uses tauri specta and an app that uses tauri specta events the program will panic
function that is responsible is
https://github.com/oscartbeaumont/tauri-specta/blob/bdab80f2e9305eed3ff4c6c0347ceed9abec94a3/src/builder.rs#L163

example here that showcases the issue
https://github.com/elefant-ai/tauri-specta/tree/broken/with-two-events/examples/custom-plugin

**Comment by oscartbeaumont** [comment]
Super my bad. Thanks @Brendonovich for fixing!

Will be release in the 24 hr or so with the new Tauri `2.0.0-rc.0` release

**Comment by n1ght-hunter** [comment]
sweet thanks
