### ISSUE TITLE
Tauri Upgrades

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/tauri-specta#126]
We could automate it but for now we can keep it manual. This PR is "closed" but I still monitor messages on it!

Just throw a message here if you want us to upgrade to the latest Tauri release.

<details>
  <summary>Script prototype</summary>
  
  ```ts
// A script to open a PR automatically updating Tauri.

(async () => {
    const resp = await fetch("https://index.crates.io/ta/ur/tauri");
    if (!resp.ok) throw new Error(`Failed to fetch Tauri from registry: ${resp.status} ${await resp.text()}`);
    const data = await resp.text();
    const versions = data.slice(0, -1).split("\n").map((v) => JSON.parse(v));

    // TODO: Semver match the latest version, argh

    // TODO: Find + replace across the codebase
})();
```
</details>

**Comment by pauliesnug** [comment]
After the finding + replacing, we should do a build and test to ensure that the bump compiles (assuming we would do this in CI on a cron job)

**Comment by oscartbeaumont** [comment]
For sure. Right now all CI isn't working so that isn't great but even a premade PR I can quickly test makes it easy.

Not sure if actually building a script will be that useful thought because Tauri will v2 pretty soon and then it won't matter but I suppose if we build it, it can potentially be reused for Tauri v3 on and on.

**Comment by pauliesnug** [comment]
@oscartbeaumont Tauri rc2 was updated but to be honest at this point I think they will do a full release soon (end of August)

**Comment by FlorianStasse** [comment]
Hello, would it be possible to update to the latest Tauri version (2.0.0-rc.8) as there have been quite some improvements for plugins in the latest releases ?
I tested it on a fork, and I only had to update tauri-build to 2.0.0-rc.7 in order for it to compile and the test to pass.
I could submit a PR if you want to, but I saw your PR template saying to ask here for any Tauri upgrade.

**Comment by oscartbeaumont** [comment]
All sorted. https://github.com/specta-rs/tauri-specta/releases/tag/v2.0.0-rc.18

Yeah, I am not asking for PR's just to ensure it's done correctly because it's easier for me to just do it than determine it was done correctly and all previous PR's missed something or another.

**Comment by pauliesnug** [comment]
rc.10 was just released lol. i wonder when they will do a full release
