### ISSUE TITLE
feat: add comments to disable linters

### ISSUE THREAD

**Issue by iMobs** [oscartbeaumont/tauri-specta#15]
Comments to disable eslint, tslint, and prettier should be added at the top of the generated bindings. Otherwise, every time the bindings are regenerated they will likely violate the style guide. Alternatively, there should be a recommendation in the README to add the generated files to the ignore list for linters.

**Comment by oscartbeaumont** [comment]
Fixed. Example [here](https://github.com/oscartbeaumont/tauri-specta/blob/e7bbbbfc61d42885b549da16547c579f6e33ab4e/example/src-tauri/src/main.rs#L65).
