### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by kiryasolod** [oscartbeaumont/tauri-specta#19]
I'm getting the following error with this generated code
`declare global {`
`    interface Window {`
`        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;`
`    }`
`}`

`const invoke = window.__TAURI_INVOKE__;`

If I change it to this
`import { invoke } from "@tauri-apps/api";`
then everything works. I'm using sveltekit for fronted

**Comment by Brendonovich** [comment]
I'm guessing SvelteKit is attempting to SSR in development mode and so `window` can't be found? We should probably lazily retrieve `__TAURI_INVOKE__` so this error could only happen if `window` wasn't defined while calling a Tauri function.

**Comment by kiryasolod** [comment]
Well, the error occurs in both dev an build scenarios. Any ideas what to do right now?

**Comment by Brendonovich** [comment]
I'm working on a fix but are you using the static adapter with SSR disabled and prerender enabled?

**Comment by kiryasolod** [comment]
Here is what I have in my routes/+layout.ts
`export const ssr = false;`
`export const prerender = true;`
`export const csr = true;`

**Comment by Brendonovich** [comment]
Try `rev = "f5021c4b5cfda9e48fc6113afad19910b259e83f"` as the version for `tauri-specta`

**Comment by kiryasolod** [comment]
It seems it works now! Should I leave this revision in my Cargo.toml or it will be better to wait for a new release version?
Thanks very much for fixing it so fast =)

**Comment by Brendonovich** [comment]
Use `rev = "9791dc005ae12d6c5248c1081044b44c1b086122"` for now, then when the next release comes out you can change it
