### ISSUE TITLE
cannot find function `export_with_cfg_with_header` in module `ts`

### ISSUE THREAD

**Issue by Walidoux** [oscartbeaumont/tauri-specta#23]
![image](https://user-images.githubusercontent.com/87608619/235664586-2d48a30c-7d7a-4eb0-9547-3f1177210ff3.png)

**Comment by Brendonovich** [comment]
`export_with_cfg_with_header` has been replaced by the `ts::Exporter` builder

**Comment by oscartbeaumont** [comment]
Will check and update the docs if we missed anywhere.

**Comment by Walidoux** [comment]
> `export_with_cfg_with_header` was replaced by the `ts::Exporter` builder in #17

The builder you've mentioned cannot be imported yet
Waiting for next release!
