### ISSUE TITLE
Optional input argument

### ISSUE THREAD

**Issue by probablykasper** [oscartbeaumont/tauri-specta#4]
Not sure how it would be done, but would be great to have the `input` be optional when a function has no argument. Currently you have to supply `null`. Setting the type to `void` might be an option.

**Comment by Brendonovich** [comment]
I don't think the solution you've suggested will work since you still need to pass an argument of type `void` (impossible), and it's similar to situations in [rspc](https://github.com/oscartbeaumont/rspc) where a query/mutation has no argument. I think some changes to the codegen I have planned could alleviate this problem though - generating a new function per command rather than `typedInvoke`.

**Comment by oscartbeaumont** [comment]
`void` wouldn't work but vardic args can be used for this similar to rspc and trpc.

**Comment by probablykasper** [comment]
Are you sure `void` wouldn't work? `undefined` is assignable to `void`. iirc it worked fine if I update the bindings. Undefined is assignable

**Comment by probablykasper** [comment]
https://github.com/microsoft/TypeScript/pull/27522
https://stackoverflow.com/questions/21120632/void-as-a-type-of-an-argument-of-a-generic-function-in-typescript

**Comment by probablykasper** [comment]
> Yeah that would work, but you'd still have to provide an argument.

That doesn't seem to be how it works. If you see the PR I linked, it made trailing `void` parameters optional

I think having discrete functions sounds amazing though, would love to see that!

**Comment by Brendonovich** [comment]
This issue shouldn't apply with 17e6c64e88bb2f9c1e7b5ef22b9f4afdd12955be.

**Comment by probablykasper** [comment]
That seems like it should work indeed, looks wonderful to use.

Now that I think about it though, the functions present a bit of a challenge for me. At the moment, I have a wrapper for invoking commands, so that I don't need a `try-catch` around every invoke call:
```js
async function runCmd(cmd, input) {
  try {
    return await invoke(cmd, input)
  } catch (e) {
    invoke('error_popup', { msg: String(e) })
    throw e
  }
}
```

Not quite sure how I should deal with that one 🤔

**Comment by Brendonovich** [comment]
@probablykasper I can seen a few ways of doing this:
Perhaps the simplest is to manually catch the promise itself and give it a function that does what you need:
```ts
import { helloWorld, errorPopup } from "./bindings";

async function main() {
  const result = await helloWorld("Test").catch(rethrowWithPopup);
}

function rethrowWithPopup(e) {
  errorPopup(String(e));
  throw e;
}
```

Alternatively, let `rethrowWithPopup` do the `try/catch` for you:
```ts
async function main() {
  const result = await rethrowWithPopup(() => helloWorld("Test"));
}

async function rethrowWithPopup(callback) {
  try {
    return await callback();
  } catch (e: any) {
    errorPopup(String(e));
    throw e;
  }
}
```

If this is all too clunky, you could get a bit crazy and use a Proxy to rewrite the underlying logic:
```ts
// utils.ts
import * as commands from "./bindings";

export const commands = new Proxy({}, {
  get: (_, property) => async (...args) => {
    try {
      return await commands[string](...args)
    } catch (e) {
      commands.errorPopup(String(e));
      throw e
    }
  }
);

// main.ts
import { commands } from "./utils";

async function main() {
  commands.helloWorld("Test");
}
```
This approach wouldn't be friendly if you're using TypeScript though.

**Comment by probablykasper** [comment]
Yeah I think something like the the last option is what I'll need to look at - I don't want to risk forgetting to handle an error

**Comment by Brendonovich** [comment]
@probablykasper This seems to work great in TS:

```ts
// utils.ts
import * as c from "./bindings";

const commands: typeof c = new Proxy({} as any, {
  get:
    (_, property: string) =>
    async (...args: any[]) => {
      try {
        return await (c as any)[property](...args);
      } catch (e) {
        c.helloWorld(String(e));
        throw e;
      }
    },
});

// main.ts
import { commands } from "./utils";

async function main() {
  commands.helloWorld("Test");
}
```
I reckon we can close this issue now.

**Comment by probablykasper** [comment]
Oh cool, I'll try it out! Thank you so much, didn't expect you to just do it all for me haha

**Comment by Brendonovich** [comment]
No worries, didn't wanna leave you without a proper solution before marking this as done haha
