### ISSUE TITLE
Enums as HashMap keys generate invalid TypeScript definitions

### ISSUE THREAD

**Issue by Raicuparta** [oscartbeaumont/tauri-specta#52]
This is the same issue as here: https://github.com/oscartbeaumont/specta/issues/65
Which was already fixed in specta 1.0.3.

For some reason, the ts file exported by tauri-specta doesn't have this fix. I even tried running just specta directly from the same project (so using the exact same specta that tauri-specta is using), and the bug doesn't happen when using `specta::ts::inline`, but is still there when going through tauri-specta.

**Comment by oscartbeaumont** [comment]
Left a reply in the other issue too.

Interesting, I'm honestly not sure why you would be having problems in tauri-specta but not Specta of the same version. I will get the next tauri-specta version out tonight and if your having problems with it would you mind creating a repository or snippet which reproduces the issue.

**Comment by Raicuparta** [comment]
@oscartbeaumont Any update on that release? If there's anything I can do to help, please let me know 🙏

**Comment by oscartbeaumont** [comment]
I seem to have missed this message but this should be fixed. If not please post a reproduction of the bug and I can look into it!
