### ISSUE TITLE
tauri with nextjs requires importing invoke from tauri-apps/api/tauri

### ISSUE THREAD

**Issue by StoicDeveloper** [oscartbeaumont/tauri-specta#63]
Currently tauri-specta generates a binding.ts file with the following line:

`         import { invoke as TAURI_INVOKE } from "@tauri-apps/api";`

When building the app `cargo tauri dev` using the NextJS framework, prerendering the app pages gives the following error:

`ReferenceError: window is not defined`

If the import is manually changed to 

`import { invoke as TAURI_INVOKE } from "@tauri-apps/api/tauri";`

Then building the app works fine.

**Comment by StoicDeveloper** [comment]
Related: https://github.com/tauri-apps/tauri/issues/7488

**Comment by SamHep0803** [comment]
Any update on this?

**Comment by Brendonovich** [comment]
This is fixed on main, it can be releases in another rc release

**Comment by oscartbeaumont** [comment]
This should be solved with Tauri v2 as the import is now `@tauri-apps/api/core`.

Will be releasing Tauri v2 support in the coming days once a few minor bugs are sorted out.

**Comment by tomocrafter** [comment]
hmm, I'm importing `invoke` from `@tauri-apps/api/core` on v2.2.1 but it seems occurring same `window is not defined` error. any news on this?
