### ISSUE TITLE
Use regular `Result` name instead of `__Result__`

### ISSUE THREAD

**Issue by Brendonovich** [oscartbeaumont/tauri-specta#69]
it's annoying + unnecessary

**Comment by dam5h** [comment]
Are you able to return a rust `Result<T, E>` from a command?  I would like to use `?` operator in commands, but thus far have had to create a custom `CommandResult<T, E>` which means no `?` operator.

**Comment by Brendonovich** [comment]
you should be able to? in 2.0 it's how we support typesafe error handling
