### ISSUE TITLE
defintive / determinative ordering of types in bindings.ts

### ISSUE THREAD

**Issue by anatawa12** [oscartbeaumont/tauri-specta#77]
tauri-specta creates bindings.ts with types in random order.
however, I want defintive / determinative ordering because I have to add bindings.ts to git repository.
During build of tauri application, rust executable is not executed before npm build (in general configuration) so I want to keep bindings.ts to git repository.

**Comment by oscartbeaumont** [comment]
Are you using v1 or v2 of Tauri Specta? I am fairly sure this is fixed in v2.

**Comment by anatawa12** [comment]
I'm using v1

**Comment by oscartbeaumont** [comment]
As discussed this is a problem with Tauri Specta v1 and the problem is within Specta v1 so it's not something we can fix unless you upgrade to Tauri Specta v2/Specta v2.

**Comment by anatawa12** [comment]
spectaa v1 will never be updated?

**Comment by oscartbeaumont** [comment]
Not at this stage.

I just don't have the capacity to maintain two versions and Specta v2/Tauri Specta v2 are both very different from their v1 counterparts.
