### ISSUE TITLE
what's the best way to generate binding for non plugin commands / events in v2?

### ISSUE THREAD

**Issue by anatawa12** [oscartbeaumont/tauri-specta#80]
I heard #77 has solved in v2 so I tried to use v2 but I could not find the option to not include `"plugin:tauri-specta|"` prefix in command names.

**Comment by anatawa12** [comment]
The generated binding always includes `"plugin:tauri-specta|"` and I think it's not needed for my use case since my project is not a tauri plugin. I'm sorry if my understanding for tauri is not enough.

**Comment by anatawa12** [comment]
In other words, I do not want to include tauri-specta in runtime build as a plugin, I want to use tauri-specta as just a typescript generator.

**Comment by oscartbeaumont** [comment]
This is fixed now. You can see how it works [here](https://github.com/oscartbeaumont/tauri-specta/blob/main/docs/v2.md#export-your-bindings).
