### ISSUE TITLE
Linked Tauri version does not compile under OSX

### ISSUE THREAD

**Issue by thurn** [oscartbeaumont/tauri-specta#92]
Attempting to follow the example in the documentation, it forces the project to use Tauri 2 Beta 17. This version does not seem to compile under OSX/rustc 1.7.8:

```
    --> /Users/me/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tauri-2.0.0-beta.17/src/webview/mod.rs:1078:5
     |
1077 |   pub fn url(&self) -> Url {
     |                        --- expected `url::Url` because of return type
1078 |     self.webview.dispatcher.url().unwrap()
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Url`, found `String`
```

The newest beta of Tauri 2 (19) does compile correctly.

**Comment by reyamir** [comment]
Look like tauri-specta is not compatible with latest tauri beta yet

**Comment by oscartbeaumont** [comment]
This doesn't appear to be a bug in Tauri Specta but in fact a bug in Tauri so going to close this.

You should open an issue in the [tauri-apps/tauri](https://github.com/tauri-apps/tauri) repository

**Comment by oscartbeaumont** [comment]
For context, this same issue is present in v19.

I don't know if you have any other features enabled but i've never observed it under v17 on macOS so maybe sharing a reproduction could help the Tauri team?

Also in the current Tauri Specta releases we hard lock the version to `2.0.0-beta.17` so despite you likely specifiying 19 in your own project v17 wins.

**Comment by thurn** [comment]
@oscartbeaumont  are you saying you *do* see this compile issue with tauri b19 and *don't* see it under b17? That's the opposite of me. It's pretty consistently reproducible for me with tauri-specta and beta17.

**Comment by oscartbeaumont** [comment]
I think I may have typed `18` not `19` when testing by mistake, sorry!

 Just checked again and b19 is good to go so did a release.
