### ISSUE TITLE
`__makeEvents__` defined but it's value is never read

### ISSUE THREAD

**Issue by kareemmahlees** [oscartbeaumont/tauri-specta#96]
## Description
I have no defined events in the backend, so `__makeEvents__` is not used.
The problem is that when building the application with `tsc` it fails throwing the following:
![image](https://github.com/oscartbeaumont/tauri-specta/assets/89863279/478739b4-ee60-440b-95fc-7724b3e2ecba)

## Desired solution
Adding a `// @ts-nocheck` at the top of the generated file will be sufficient, and even maybe add eslint ignore comments as well.

## Environment info
- tauri-specta: 2.0.0-rc.5
- tsc: 5.4.2

**Comment by oscartbeaumont** [comment]
Given we can't account for all different configurations and tools we allow the user to define their own header for the file.

You can do the following:
```rust
let builder = ts::builder()
            .commands(...)
            .header("// @ts-nocheck\n"); // <- This this appended to the start of the file
```

As of the current release you will need a `\n` to ensure it doesn't end up on the same line as the first line of Tauri Specta's runtime however I have fixed that for the next release.

**Comment by oscartbeaumont** [comment]
I've also added a section to the v2 docs because it was definitely unclear how to solve this before.
